# Generated by Django 4.1.2 on 2023-06-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='tech',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
