# Generated by Django 4.2.7 on 2023-12-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_skill_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endorse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email_id', models.EmailField(max_length=254)),
                ('endorsement', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
