# Generated by Django 4.1 on 2024-06-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_endorse_alter_skill_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=3000, null=True)),
                ('url', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
