# Generated by Django 4.1 on 2024-06-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='experience',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
